services:
  roblox_bot_1:
    image: node:18
    working_dir: /app
    volumes:
      - ./open-roblox.js:/app/open-roblox.js
    entrypoint: >
      bash -c "npm install puppeteer && node open-roblox.js"
